from pathlib import Path

from .analyzer import (
    analyze_pcap,
    get_length_distribution,
    get_top_ports,
    get_service_name,
)
from .charts import (
    generate_length_chart,
    generate_port_chart,
    generate_conversation_diagram,
    generate_length_mermaid,
    generate_port_mermaid,
    mermaid_to_png,
)


def generate_report(stats, input_file, output_file, generate_png=True):
    """Generate markdown report with analysis results"""

    base_path = Path(output_file).stem

    if stats.get("lengths"):
        generate_length_chart(stats, f"{base_path}_length.png")

    if stats.get("port_stats"):
        generate_port_chart(stats, f"{base_path}_port.png")

    if stats.get("conversations"):
        generate_conversation_diagram(stats, f"{base_path}_conversation.png")

    mermaid_conv = generate_conversation_diagram(stats, None)
    mermaid_length = generate_length_mermaid(stats)
    mermaid_port = generate_port_mermaid(stats)

    avg_len = stats.get("total_bytes", 0) / max(stats.get("total_packets", 1), 1)

    markdown = f"""# Network Capture Analysis Report

**Input File**: {input_file}
**Generated**: {Path(output_file).name}

---

## Summary Statistics

| Metric | Value |
|--------|-------|
| Total Packets | {stats.get("total_packets", 0):,} |
| Total Bytes | {stats.get("total_bytes", 0):,} |
| Average Packet Length | {avg_len:.2f} bytes |

---

## Protocol Distribution

| Protocol | Packet Count |
|----------|---------------|
"""

    for proto, count in sorted(
        stats.get("protocols", {}).items(), key=lambda x: x[1], reverse=True
    ):
        markdown += f"| {proto} | {count:,} |\n"

    markdown += f"""

---

## Packet Length Distribution

![Packet Length Distribution]({base_path}_length.png)

```mermaid
{mermaid_length}
```

---

## Top Destination Ports

![Top Ports]({base_path}_port.png)

| Port | Service | Count |
|------|---------|-------|
"""

    for port, data in get_top_ports(stats, 10):
        markdown += f"| {port} | {get_service_name(port)} | {data['count']:,} |\n"

    markdown += f"""

```mermaid
{mermaid_port}
```

---

## Conversation Pairs

![Conversations]({base_path}_conversation.png)

### UML Sequence Diagram

```mermaid
{mermaid_conv}
```

---

## Conversation Details

| Source | Destination | Packets | Bytes | Protocols |
|--------|-------------|---------|-------|-----------|
"""

    conversations = stats.get("conversations", {})
    sorted_convs = sorted(
        conversations.items(), key=lambda x: x[1]["packets"], reverse=True
    )[:20]

    for key, data in sorted_convs:
        protocols = ", ".join(data.get("protocols", set()))
        markdown += f"| {data['src']}:{data.get('src_port', 0)} | {data['dst']}:{data.get('dst_port', 0)} | {data['packets']:,} | {data['bytes']:,} | {protocols} |\n"

    markdown += """

---

*Report generated by NetCap Analysis Tool*
"""

    Path(output_file).write_text(markdown)
